// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljcgevwbfyvbbzpdsnri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqY2dldndiZnl2YmJ6cGRzbnJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTk4MjAsImV4cCI6MjA2MTM5NTgyMH0.FuJEVPRxraMuyEeX42dk6ac1XyqSpm1SMhBtMuDkgiQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);